### ISSUE TITLE
What do you do with the chess data?

### ISSUE THREAD

**Issue by ran88dom99** [Andreilys/personal_dashboard#2]
I am researching the usefulness of chess for QS. What data do you get from lichess and what do you use it for? Also look at my dataflow network.

**Comment by Andreilys** [comment]
I haven't used it much, I believe it just had my win/loss rate and how often I played.

Here are a couple of other related projects:
https://github.com/markwk/qs_ledger
https://github.com/karlicoss/HPI
https://github.com/woop/awesome-quantified-self
